gateways:
    local:
        connection:
            type: postgres
            host: localhost
            user: postgres
            password: password
            port: 5432
            database: db

default_gateway: local

model_defaults:
    dialect: postgres
